"use client";

import { Download, Link } from "lucide-react";

export default function DownloadSummaryButton({ summary }: { summary: object }) {

  const handleDownload = () => {
    const summaryContent = `# ${summary?.title}
Generated Summary
Generated on: ${new Date(summary?.created_at).toLocaleDateString()}

${summary?.summary_text}

Orignial File: ${summary.file_name}
Generated by SumAI!
    `

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${summary?.title.replace(/[^a-z0-9]/gi,'-')}.txt`; // Or use a dynamic name
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <button
      onClick={handleDownload}
      className="flex justify-center items-center px-2 py-[5px] rounded-lg bg-rose-200"
    >
      <Download className="mx-2 text-rose-600" size={20} />
      <p className="text-rose-800 font-semibold">Download Summary</p>
    </button>
  );
}
